// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKek5Prp_BWwP1ivytERf_-d59wwSyKdg',
    appId: '1:716610357517:web:58e13c89ca6b9b8f388844',
    messagingSenderId: '716610357517',
    projectId: 'company-task-35b7d',
    authDomain: 'company-task-35b7d.firebaseapp.com',
    storageBucket: 'company-task-35b7d.firebasestorage.app',
    measurementId: 'G-1SWQHMLSFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4zGK0-8k9bLS7Vi6fF-lS4joJmhd77c',
    appId: '1:716610357517:android:da6d0f68359cafbb388844',
    messagingSenderId: '716610357517',
    projectId: 'company-task-35b7d',
    storageBucket: 'company-task-35b7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk7m_SCQTbiSRLhK1FT5R-JAw5QQJ4BEw',
    appId: '1:716610357517:ios:116c1b311872a779388844',
    messagingSenderId: '716610357517',
    projectId: 'company-task-35b7d',
    storageBucket: 'company-task-35b7d.firebasestorage.app',
    iosBundleId: 'com.example.companyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk7m_SCQTbiSRLhK1FT5R-JAw5QQJ4BEw',
    appId: '1:716610357517:ios:116c1b311872a779388844',
    messagingSenderId: '716610357517',
    projectId: 'company-task-35b7d',
    storageBucket: 'company-task-35b7d.firebasestorage.app',
    iosBundleId: 'com.example.companyTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKek5Prp_BWwP1ivytERf_-d59wwSyKdg',
    appId: '1:716610357517:web:b8667418c9d3f4b4388844',
    messagingSenderId: '716610357517',
    projectId: 'company-task-35b7d',
    authDomain: 'company-task-35b7d.firebaseapp.com',
    storageBucket: 'company-task-35b7d.firebasestorage.app',
    measurementId: 'G-EEW11816JQ',
  );
}
